### ISSUE TITLE
Modded MxUpdate Tool package for V6R2013x

### ISSUE THREAD

**Issue by yrttiaho** [MxUpdate/Update#201]
Please find package that we are using until project implements officially those functionalities that we are in need from it.
![mxupdate-0 91 0-modded-install zip](https://cloud.githubusercontent.com/assets/5764060/2786417/6eff573c-cb75-11e3-8f25-58bad31c6da4.jpg)

Please note! File extension needs to be as zip.

**Comment by moxter** [comment]
all stuff should be included now in V1.0.0
