### ISSUE TITLE
Policy CI does not export filters, approver, ignore and reject of signatures

### ISSUE THREAD

**Issue by jeschr** [MxUpdate/Update#203]
E.g. filters for signatures are not exported because they are no more below stateDefList/stateDef/signatureDefList/signatureDef/expressionFilter. Instead they are now referenced below stateDefList/stateDef/userAccessList/userAccess/expressionFilter with userAccessKey matching the signature name. There are also a lot more unknown settings:

MQL<4>exec prog MxUpdate -e --policy "Material Color Approval" --path c:\temp\test

export policy 'Material Color Approval'
WARNING! Url '/policy/majorsequence' unknown and not parsed!
WARNING! Url '/policy/delimiter' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/majorrevisionable' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/matchOrganization' with value 'any' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/matchProject' with value 'any' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/matchOwner' with value 'any' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/matchReserve' with value 'any' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/matchMaturity' with value 'any' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/matchCategory' with value 'any' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/userAccessKey' with value 'Cancelled' unknown and not parsed!
WARNING! Url '/policy/stateDefList/stateDef/userAccessList/userAccess/matchOrganization' with value 'any' unknown and not parsed!
...

**Comment by moxter** [comment]
This belongs also to approve / ignore / reject users of a signature.

**Comment by v1690117** [comment]
Hello! I also ahve this problem with latest release of MxUpdate and R2016x
What I have:
signature "AssigneeApprovalToFinanceReview" {
            branch "FinanceReview"
            approve {}
            ignore {}
            reject {}
            filter ""
        }
What I really need:
signature "AssigneeApprovalToFinanceReview" {
            branch "FinanceReview"
            approve {}
            ignore {}
            reject {}
            filter "attribute[Branch To]=='FinanceReview'"
        }
Thank you!
