### ISSUE TITLE
Properties like "original name", "installer", ... are missing in CIs when using develop branch version

### ISSUE THREAD

**Issue by jeschr** [MxUpdate/Update#232]
After installing MxUpdate from the develop branch and exporting the schema properties like "original name", "installer", ... are missing in exported tcl file. This is due to method "prepare" in AbstractAdminObject_mxJPO which compares the enum plain to the property name. Instead it should translate the enum to the property name before comparing (see attached fix which solves the issue)
![abstractadminobject_mxjpo](https://cloud.githubusercontent.com/assets/7577275/9869215/f95d97c0-5b81-11e5-8d1d-bda4781d7307.png)

**Comment by moxter** [comment]
The issue is in the development stream and already solved in the not public stream.
