### ISSUE TITLE
Abstract relationships as well as relatioships hierarchy not supported

### ISSUE THREAD

**Issue by AC-V** [MxUpdate/Update#233]
If you define an abstract relationship as a holder for a few common relationships, then MxUpdate didn't export such definition correctly.

After trying to import the exported file - an error thrown out.
![abstract_relationships](https://cloud.githubusercontent.com/assets/10960053/12593507/7f071856-c482-11e5-9f7e-bd92db79951e.png)

**Comment by moxter** [comment]
duplicated to #184
