### ISSUE TITLE
Attribute with dimension can't be updated

### ISSUE THREAD

**Issue by volker-rode** [MxUpdate/Update#235]
When you assign a dimension to an attribute of type real and update this attribute a second time (without changing the script file) then you will get an exception like the following:
[info] java.lang.Exception: If dimension 'DSDim_TEMPRTRE' is changed to new dimension '' some information could be lost!

Tested with Enovia versions V6R2013x & V6R2015x.

**Comment by moxter** [comment]
Can not be reproduced with new MxUpdate version.
