### ISSUE TITLE
Use of MxUpdate on production

### ISSUE THREAD

**Issue by v1690117** [MxUpdate/Update#266]
Hello! Thanks for the MxUpdate tool!

Clause 3.1 of MxUpdate License declares 

> "It may NOT be used on the Licensee's production systems". 

I understand this statement in this way: I am Licensee and I can't use MxUpdate on the production.

But clause 7.8 says 

> "Without the necessary configuration / parameterization by the Licensee and sufficient tests, the software shall not be suitable forthwith for use on the Licensee's production system. The Licensee undertakes to sufficiently test the software prior to use on its production system, in particular to monitor the disruption-free application of the software in a suitable test environment". 

It looks like it is assumed that we are using MxUpdate on the production.

So, the question is could I use MxUpdate on the production systems or not? If not, how could I retrieve permission (license) for use of MxUpdate on production server?

**Comment by moxter** [comment]
7.8 is only about what the Licensee must do if he use the software.
What you need is the right to use. This is defined in §3 2.:
The Licensee may use the software EXCLUSIVELY for internal development, testing or demonstration purposes. Use for deploying / distributing adjustments to MX on the Licensor's production system is PROHIBITED. .

=> So, no, you are not allowed to use MxUpdate on production server.

**Comment by v1690117** [comment]
Thanks for the answer!
Is it possible to get such permission somehow? Buy or smth?
